// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesApp.Data;

#nullable disable

namespace SalesApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250224144011_setUp")]
    partial class setUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesApp.Models.SalesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AppointmentCloseRate")
                        .HasColumnType("real");

                    b.Property<float>("AppointmentSetRate")
                        .HasColumnType("real");

                    b.Property<int>("InventoryLevels")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewVehicleSales")
                        .HasColumnType("int");

                    b.Property<int>("UsedVehicleSales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("salesDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
