// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesApp.Data;

#nullable disable

namespace SalesApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250225031915_againsetup")]
    partial class againsetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesApp.Models.SalesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AppointmentCloseRate")
                        .HasColumnType("real");

                    b.Property<float>("AppointmentSetRate")
                        .HasColumnType("real");

                    b.Property<int>("InventoryLevels")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewVehicleSales")
                        .HasColumnType("int");

                    b.Property<int>("UsedVehicleSales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalesData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentCloseRate = 8.5f,
                            AppointmentSetRate = 15.2f,
                            InventoryLevels = 500,
                            Month = "December 2023",
                            NewVehicleSales = 120,
                            UsedVehicleSales = 80
                        },
                        new
                        {
                            Id = 2,
                            AppointmentCloseRate = 8.7f,
                            AppointmentSetRate = 14.8f,
                            InventoryLevels = 480,
                            Month = "January 2024",
                            NewVehicleSales = 130,
                            UsedVehicleSales = 90
                        },
                        new
                        {
                            Id = 3,
                            AppointmentCloseRate = 7.9f,
                            AppointmentSetRate = 13.5f,
                            InventoryLevels = 460,
                            Month = "February 2024",
                            NewVehicleSales = 110,
                            UsedVehicleSales = 85
                        },
                        new
                        {
                            Id = 4,
                            AppointmentCloseRate = 9.1f,
                            AppointmentSetRate = 16f,
                            InventoryLevels = 440,
                            Month = "March 2024",
                            NewVehicleSales = 140,
                            UsedVehicleSales = 95
                        },
                        new
                        {
                            Id = 5,
                            AppointmentCloseRate = 9.3f,
                            AppointmentSetRate = 16.8f,
                            InventoryLevels = 420,
                            Month = "April 2024",
                            NewVehicleSales = 150,
                            UsedVehicleSales = 100
                        },
                        new
                        {
                            Id = 6,
                            AppointmentCloseRate = 9.5f,
                            AppointmentSetRate = 17.2f,
                            InventoryLevels = 400,
                            Month = "May 2024",
                            NewVehicleSales = 160,
                            UsedVehicleSales = 105
                        },
                        new
                        {
                            Id = 7,
                            AppointmentCloseRate = 9f,
                            AppointmentSetRate = 16.5f,
                            InventoryLevels = 380,
                            Month = "June 2024",
                            NewVehicleSales = 155,
                            UsedVehicleSales = 110
                        },
                        new
                        {
                            Id = 8,
                            AppointmentCloseRate = 10f,
                            AppointmentSetRate = 18f,
                            InventoryLevels = 360,
                            Month = "July 2024",
                            NewVehicleSales = 170,
                            UsedVehicleSales = 115
                        },
                        new
                        {
                            Id = 9,
                            AppointmentCloseRate = 10.2f,
                            AppointmentSetRate = 18.5f,
                            InventoryLevels = 340,
                            Month = "August 2024",
                            NewVehicleSales = 180,
                            UsedVehicleSales = 120
                        },
                        new
                        {
                            Id = 10,
                            AppointmentCloseRate = 10.5f,
                            AppointmentSetRate = 19f,
                            InventoryLevels = 320,
                            Month = "September 2024",
                            NewVehicleSales = 190,
                            UsedVehicleSales = 125
                        },
                        new
                        {
                            Id = 11,
                            AppointmentCloseRate = 11f,
                            AppointmentSetRate = 19.8f,
                            InventoryLevels = 300,
                            Month = "October 2024",
                            NewVehicleSales = 200,
                            UsedVehicleSales = 130
                        },
                        new
                        {
                            Id = 12,
                            AppointmentCloseRate = 11.3f,
                            AppointmentSetRate = 20.2f,
                            InventoryLevels = 280,
                            Month = "November 2024",
                            NewVehicleSales = 210,
                            UsedVehicleSales = 135
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
